/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : string,
  'paymentMethod' : string,
  'edition' : string,
  'isEarlyBird' : boolean,
  'address' : string,
  'timestamp' : bigint,
  'phone' : string,
  'pricePaid' : bigint,
  'pincode' : string,
}
export interface Stats {
  'totalOrders' : bigint,
  'baseOrders' : bigint,
  'premiumOrders' : bigint,
  'totalProfit' : bigint,
  'totalRevenue' : bigint,
  'earlyBirdUsed' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrdersByPhone' : ActorMethod<[string], Array<Order>>,
  'getStats' : ActorMethod<[], Stats>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [string, string, string, string, string, string],
    string
  >,
  'updateOrderStatus' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];