/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CancelRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'customerPhone' : IDL.Text,
  'orderId' : IDL.Text,
  'timestamp' : IDL.Int,
  'customerEmail' : IDL.Text,
  'requestType' : IDL.Text,
  'reason' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'edition' : IDL.Text,
  'isEarlyBird' : IDL.Bool,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : IDL.Int,
  'customName' : IDL.Text,
  'phone' : IDL.Text,
  'pricePaid' : IDL.Nat,
  'pincode' : IDL.Text,
  'examType' : IDL.Text,
  'bonusPages' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Stats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'baseOrders' : IDL.Nat,
  'eliteOrders' : IDL.Nat,
  'premiumOrders' : IDL.Nat,
  'totalProfit' : IDL.Nat,
  'pendingCancelRequests' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'earlyBirdUsed' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearOrders' : IDL.Func([IDL.Bool], [IDL.Nat], []),
  'getAllCancelRequests' : IDL.Func([], [IDL.Vec(CancelRequest)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEarlyBirdCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getOrderById' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrdersByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getOrdersByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitCancelRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateCancelRequest' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CancelRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'customerPhone' : IDL.Text,
    'orderId' : IDL.Text,
    'timestamp' : IDL.Int,
    'customerEmail' : IDL.Text,
    'requestType' : IDL.Text,
    'reason' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'edition' : IDL.Text,
    'isEarlyBird' : IDL.Bool,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : IDL.Int,
    'customName' : IDL.Text,
    'phone' : IDL.Text,
    'pricePaid' : IDL.Nat,
    'pincode' : IDL.Text,
    'examType' : IDL.Text,
    'bonusPages' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Stats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'baseOrders' : IDL.Nat,
    'eliteOrders' : IDL.Nat,
    'premiumOrders' : IDL.Nat,
    'totalProfit' : IDL.Nat,
    'pendingCancelRequests' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'earlyBirdUsed' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearOrders' : IDL.Func([IDL.Bool], [IDL.Nat], []),
    'getAllCancelRequests' : IDL.Func([], [IDL.Vec(CancelRequest)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEarlyBirdCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getOrderById' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrdersByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getOrdersByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitCancelRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'updateCancelRequest' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };